### ISSUE TITLE
Class Diagram Harmonisation

### ISSUE THREAD

**Issue by ilgazer** [bounswe/bounswe2023group1#102]
After the completion of the diffeerent class diagrams in #100, #95, #91 and Coordinator, the different classes will need to be harmonised into a cohesive class diagram.

**Comment by kubraaksux** [comment]
From requirements we saw that Info class is missed. @furknbulbul and I added Info class to use case diagrams and class diagrams.
I revisioned class diagrams and added method parameters and return types.

**Comment by kubraaksux** [comment]
1.1.2.2.6 Coordinators shall be able to view all user profiles, actions, calls, and information provided by facilitators. 
— What has been implied by call?
By discussing @alperenDagi call is clarified.

**Comment by HarunErgen** [comment]
Class diagrams harmonized and completed. Thanks for the effort!
