### ISSUE TITLE
Victim's Mock Up and Use Case revision

### ISSUE THREAD

**Issue by alperenDagi** [bounswe/bounswe2023group1#103]
Creating connection with facilitator and user profile is unnecessary. Victims should just give information about current situation of themselves, get notified about nearby resources and, see the resources on the map. This was talked in the meetings and this was also talked by the customer Suzan Üsküdarlı.

**Comment by kubraaksux** [comment]
I see holding victim role as simple is a better way also referring to the meetings with Suzan Üsküdarlı. But creating connection with facilitator and user profile was an idea resulted from our group meetings. Also victim-1 facilitater connection request or victim- many facilitater connection request was a further debate coming from here. 

My mock up designs for victim showing the process and I was thinking about the chat in the group meeting while doing it.

So what is the true way of come to the conclusion considering those?

Connection wasn't active chat. It was for representation of victim as I remember. Do we have any notice about that in group meeting notes?

 It should be meeting 8.

**Comment by ilgazer** [comment]
> Do we have any notice about that in group meeting notes?

As far as I can see, the connection feature was not mentioned in the meeting 8 minutes. I do remember that the idea was raised, but I believe no consensus was reached. 

In any case, the customer has been signalling to us that they don't find the victim role central to the project. As such I feel like it would be best to ask the customer if this feature is essential, and drop the feature if not.

**Comment by kubraaksux** [comment]
Finalised victim mockup and scenario according to the final version of victim role as discussed. Its convenient with the requirements current versiın.

**Comment by kubraaksux** [comment]
Finalised mockup diagrams according to the requirements and meetings. 
Also for victim, mobile mockups are created since for the victim it is more convenient to use mobile rather than web.
You can check my work here:
https://www.figma.com/file/LmUQJGetWO7oD8qCHAwtbl/Disaster-Response-Platform-Roles?node-id=0%3A1&t=IHRxdOnZV17GCxfa-1

**Comment by kubraaksux** [comment]
Use case revision for victim role is done by me and @furknbulbul
