### ISSUE TITLE
Use Case Diagram - Coordinater

### ISSUE THREAD

**Issue by kubraaksux** [bounswe/bounswe2023group1#107]
Improve the Use Case Diagram for the Coordinator role in the disaster response platform to accurately depict their responsibilities and interactions with other actors in the system.

**Comment by furknbulbul** [comment]
I think it is mostly done, @HarunErgen did an outstanding job. It would be nice to have a meeting about the coordinator revision before we make a general use case revision as a group. What do you think guys @cemsarpkaya  @kubraaksux?

**Comment by kubraaksux** [comment]
Meeting for coordinator use case has been done. Evaluations and little changes have been occurred with @furknbulbul
