### ISSUE TITLE
Glossary Revision

### ISSUE THREAD

**Issue by HarunErgen** [bounswe/bounswe2023group1#113]
Glossary should be revisioned according to the decisions taken at [Meeting 10](https://github.com/bounswe/bounswe2023group1/wiki/Meeting-10-(04.04.2023)).

**Comment by alperenDagi** [comment]
Applied changes according to meeting 10 notes. Additionally added 'Information' to glossary.

**Comment by kubraaksux** [comment]
revisioned information from glossary since the class added later by me and @furknbulbul
