### ISSUE TITLE
Sequence Diagram #1 - #6

### ISSUE THREAD

**Issue by volcaniqueo** [bounswe/bounswe2023group1#120]
Creating six different sequence diagrams using class diagrams.

**Comment by volcaniqueo** [comment]
See the completed diagrams [here](https://github.com/bounswe/bounswe2023group1/wiki/Sequence-Diagrams).

**Comment by kubraaksux** [comment]
#117 mark your scenarios here

**Comment by alitpc25** [comment]
Updated the #6 diagram so that it contains more functionality that can be used by the user.
