### ISSUE TITLE
Created Milestone Report 1 First Draft

### ISSUE THREAD

**Issue by kubraaksux** [bounswe/bounswe2023group1#121]
https://github.com/bounswe/bounswe2023group1/wiki/Milestone-1-Report
This is first draft of our report. Necessary edits should be done by the whole team. 

    -  Also i have added the Milestone Report to our wiki and sidebar.

**Comment by kubraaksux** [comment]
Made second edition on Milestone report. Still way to go.

**Comment by kubraaksux** [comment]
Added individual contribution reports section to wiki and sidebar. Everyone is responsible for theirs.

**Comment by alitpc25** [comment]
Prepared the main page for the report which includes:
* A section for self-introduction with the course name, group number, and contributors.
* Table of Contents
* Executive Summary: Summary of project status and any changes in plans based on reflections.
* List and status of deliverables.
* Evaluation of the status of deliverables and its impact on your project plan.
* Evaluation of tools and processes that you have used to manage your team project.
* Individual Contribution Reports. (a list of member contributions in alphabetic order by member SURNAME. See description of individual reports below).

Revision is needed and also we need to create more pages for individual reports and deliverables.
