### ISSUE TITLE
Create Sequence Diagram: Create Request

### ISSUE THREAD

**Issue by ilgazer** [bounswe/bounswe2023group1#123]
Creating a sequence diagram using plantUML for creating a request as per #117

**Comment by ilgazer** [comment]
![image](https://user-images.githubusercontent.com/7621539/230805790-2a44d62d-b199-4d12-8632-68898f9cdd8a.png)

@startuml
facilitator -> Map: viewResources(latitude, longtitude)
facilitator <-- Map: resourcesList
facilitator -> Request: Request(creationDate, updateDate, location, urgency, requester, resources)
Facilitator <-- Request: createdRequest
@enduml

Needs revision!

**Comment by kubraaksux** [comment]
I reviewed your work. I think there is no problem. Ready to go! Can you add these to sequence diagram facilitator issue?

**Comment by furknbulbul** [comment]
I had added one sequence diagram related to creating request, it has a little more details. #13 in the sequence diagrams

**Comment by ilgazer** [comment]
@furknbulbul can we perhaps merge the two? I think you can just copy the bits that interact with the map to your diagram and then we close this one.

**Comment by HarunErgen** [comment]
Sequence diagrams have been added to the Milestone 1 Report. Thank you all for your efforts.
