### ISSUE TITLE
Create Sequence Diagram: Notifications

### ISSUE THREAD

**Issue by ilgazer** [bounswe/bounswe2023group1#124]
Creating a sequence diagram using plantUML for retrieving notifications as per #117

**Comment by ilgazer** [comment]
![image](https://user-images.githubusercontent.com/7621539/230806159-9f9d58d6-2b9e-4258-a81d-cb30071aee8c.png)

@startuml

user -> User: viewNotifications()
user <-- User: notifications
user -> Notification: getMessage()
user -> Notification: getDate()
user <-- Notification: message
user <-- Notification: date
user -> User: dismissNotification(notification)

@enduml

Needs feedback!

**Comment by kubraaksux** [comment]
I reviewed your work. I think there is no problem. Ready to go!

**Comment by ilgazer** [comment]
Changed actor icon to stickman and added to the wiki page.
