### ISSUE TITLE
Create Sequence Diagram: Assign Action

### ISSUE THREAD

**Issue by ilgazer** [bounswe/bounswe2023group1#125]
Creating a sequence diagram using plantUML for coordinator assigning an action as per #117

**Comment by ilgazer** [comment]
![image](https://user-images.githubusercontent.com/7621539/230807298-8aad5ca4-9f7d-402e-a9c4-0cbd89fd0db7.png)

@startuml

responder -> Responder: viewTasks()
responder <-- Responder: taskList
responder -> Responder: declineTask(task)
responder -> Responder: acceptTask(task)
responder -> Task: viewActionList()
responder <-- Task: actionList
responder -> Action: getActionType()
responder <-- Action: "go to location"
responder -> Action: viewActionPath()
responder <-- Action: locationList
responder -> Action: selectAction()
responder -> responder: Go to location in real life
responder -> Action: setCompleted(true)
facilitator -> Action: setVerified(true)
@enduml

Needs revision. @volcaniqueo this supersedes your first sequence diagram, maybe you take a look

**Comment by kubraaksux** [comment]
I reviewed your work. I think there is no problem. Ready to go!

**Comment by kubraaksux** [comment]
Can you add this to sequence diagram coordinator issue too?

**Comment by ilgazer** [comment]
Added actor stickman and and put it on the wiki page
