### ISSUE TITLE
Create Sequence Diagram: User Views and Edits Profile

### ISSUE THREAD

**Issue by alitpc25** [bounswe/bounswe2023group1#127]
Creating a sequence diagram using diagrams.net for user viewing/editing his/her profile.

**Comment by alitpc25** [comment]
![viewEditProfile](https://user-images.githubusercontent.com/42305974/230812344-b89231f7-3a5e-40a1-b63a-18331df3dc9c.png)
Completed.

**Comment by kubraaksux** [comment]
#117 mark your diagrams here
