### ISSUE TITLE
Create Sequence Diagram: User login/logout.

### ISSUE THREAD

**Issue by alitpc25** [bounswe/bounswe2023group1#128]
Creating a sequence diagram using diagrams.net for users' login/logout functionalities.

**Comment by alitpc25** [comment]
![login](https://user-images.githubusercontent.com/42305974/230812495-887a563b-5225-4f42-898e-566cf2848be1.png)
![logout](https://user-images.githubusercontent.com/42305974/230812503-4bf017d8-2a45-48c2-82f6-1c5acc26ce7e.png)

Completed.

**Comment by kubraaksux** [comment]
#117  mark your scenarios here
