### ISSUE TITLE
Create Sequence Diagram: Profile Register - Verification

### ISSUE THREAD

**Issue by kubraaksux** [bounswe/bounswe2023group1#144]
Creating a sequence diagram using plantUML for an admin reviewing applications as per #117.

@startuml
actor User
participant Profile
database Database

User -> Profile: register(username, password, email)
Profile -> Database: addUser(username, password, email)

alt successful case

    Database -> Profile: isUserAdded (boolean):
    Profile -> User: verification_code
    User -> Profile: verifyEmail(verification_code)
    Profile -> Database: updateUserStatus(username, verified)
    
    Database -> Profile: isUserStatusUpdated (boolean):
    Profile -> User: boolean (verification successful)

    else some kind of failure

        Profile -> User: boolean (verification failed)

else Another type of failure

    Profile -> User: boolean (registration unsuccessful)

end
@enduml

**Comment by kubraaksux** [comment]
![seq-1](https://user-images.githubusercontent.com/67320250/230912507-69a4c3d0-6ac0-4e31-b447-80223be60127.png)

**Comment by ilgazer** [comment]
Nice work! I think the only slight change this needs is adding the stickman symbol to the actor. You can do that by simply saying `actor user` immediately after the @startuml. Also, were we supposed to have the database interactions for this milestone? We didn't have a database in our UML diagram so I made my diagrams without a database.

**Comment by kubraaksux** [comment]
I first made my diagrams without database, then @GulbeycanCagri commented on that about it is better with database and our slides have that database view. So I changed it.

**Comment by kubraaksux** [comment]
![seqqqqqq1](https://user-images.githubusercontent.com/67320250/230958619-6b621ed7-0cb8-4916-8ca4-7d88a73987cc.png)

**Comment by kubraaksux** [comment]
@ilgazer thank you for your comments. This is the final version of my sequence diagram

**Comment by ilgazer** [comment]
Ok perfect, this looks correct :)
