### ISSUE TITLE
Create Sequence Diagram: Admin - Coordinater Assign

### ISSUE THREAD

**Issue by kubraaksux** [bounswe/bounswe2023group1#145]
Creating a sequence diagram using plantUML for an admin reviewing applications as per https://github.com/bounswe/bounswe2023group1/issues/117.

@startuml
actor Admin
participant Coordinator
participant User

Admin -> Coordinator: assignCoordinator(userID)
Coordinator --> Admin: boolean (coordinator assignment successful)
Admin -> User: viewUserProfile(userID)
User --> Admin: displayProfile()
@enduml

**Comment by kubraaksux** [comment]
![seqq2](https://user-images.githubusercontent.com/67320250/230922600-354a626b-147f-4b75-8f11-458871c5b080.png)

**Comment by ilgazer** [comment]
Nice work! However, I feel like the application workflow is already covered in #122 . Do you have any ideas on how to make this one more distinct?

**Comment by kubraaksux** [comment]
I created #117 to prohibit this confusion and announced the group multiple times. Work share has been done at meeting 11 and that was my duty to do.

**Comment by kubraaksux** [comment]
Actually they are different scenarios.

**Comment by ilgazer** [comment]
Ok sure. One more question, why is the Coordinator supposed to be an actor(the human interacting) or the Coordinator object? I think it's the second one.

**Comment by kubraaksux** [comment]
![seqo](https://user-images.githubusercontent.com/67320250/230970182-f4fb8d3d-2518-4892-a379-3afd69e339be.png)
