### ISSUE TITLE
Create Sequence Diagram: Coordinater - Responder Task Assign

### ISSUE THREAD

**Issue by kubraaksux** [bounswe/bounswe2023group1#146]
Creating a sequence diagram using plantUML for an admin reviewing applications as per #117 

@startuml
actor Responder
actor Coordinator
participant Task

Coordinator -> Task: createTask(responder, task)
Coordinator <-- Task: taskID
Coordinator -> Task: assign(responder)
Task -> Responder: setAssignee(responder)
@enduml

**Comment by kubraaksux** [comment]
![reqq3](https://user-images.githubusercontent.com/67320250/230923193-b5ec5b69-0fc4-4a10-98d0-3976e8175aaa.png)

**Comment by ilgazer** [comment]
The diagram looks nice! But I couldn't see a setAssignee method in Responder in the class diagram and I'm not sure if it makes sense to have one. Am I missing something?

**Comment by kubraaksux** [comment]
task has setAssignee method
