### ISSUE TITLE
Create Sequence Diagram: Responder - Action - Feedback

### ISSUE THREAD

**Issue by kubraaksux** [bounswe/bounswe2023group1#147]
Creating a sequence diagram using plantUML for an admin reviewing applications as per https://github.com/bounswe/bounswe2023group1/issues/117.

@startuml
actor responder
participant Responder
participant Task
participant Action

responder -> Responder: acceptTask(taskID)
Responder -> Task: setAssignee(responder)
Responder -> Task: updateTaskStatus(taskID, newStatus)
responder -> Action: setCompleted(newStatus)
responder -> Action: giveFeedback(taskID, message)
@enduml

**Comment by kubraaksux** [comment]
![reqq4](https://user-images.githubusercontent.com/67320250/230923772-25dd59a2-41be-4b98-9932-da52edb4c277.png)

**Comment by ilgazer** [comment]
Hey! I think you might want to double check this one with the class diagram. I can't find a giveFeedback function there.

**Comment by kubraaksux** [comment]
Action class has  "+ giveFeedback(feedback: Feedback): void" method.
