### ISSUE TITLE
Creating Introduction Page Templates

### ISSUE THREAD

**Issue by alperenDagi** [bounswe/bounswe2023group1#18]
Create introduction page template considering meeting 2

**Comment by alperenDagi** [comment]
created introduction page templates according to our discussion

**Comment by kubraaksux** [comment]
> created introduction page templates according to our discussion

as revisioner i appreciate your work my colleague

**Comment by kubraaksux** [comment]
hey alperen, what you think if we visualize our personal pages a little bit more? some ideas 
<img width="196" alt="Screenshot 2023-03-12 at 21 32 25" src="https://user-images.githubusercontent.com/67320250/224565134-59101d95-737e-4e06-af4e-f94cdb6edbe4.png">
<img width="314" alt="Screenshot 2023-03-12 at 21 33 04" src="https://user-images.githubusercontent.com/67320250/224565139-0d51a8ee-95fd-43e2-854e-b4c3d1e7c961.png">
<img width="180" alt="Screenshot 2023-03-12 at 21 33 08" src="https://user-images.githubusercontent.com/67320250/224565143-72ef023e-e98c-445e-bb90-1fd6674ae742.png">
