### ISSUE TITLE
Frontend - Backend connection on Docker

### ISSUE THREAD

**Issue by alitpc25** [bounswe/bounswe2023group1#180]
Frontend and Backend connections are working on local, but when trying on Docker with docker-compose up, frontend and backend both works but their connections is not working. For example it gives error "Could not proxy request /getDirection?from=bogazici&to=it%C3%BC from localhost:3000 to http://localhost:4000/"

**Comment by ilgazer** [comment]
Migrating the whole hosting setup to nginx instead of using the proxy feature of react should fix this issue.
