### ISSUE TITLE
Swagger is not accessible

### ISSUE THREAD

**Issue by ilgazer** [bounswe/bounswe2023group1#203]
We cannot access swagger from http://localhost/api/swagger-ui/index.html but the new address http://localhost/api doesn't work with swagger. The URL http://localhost/api/swagger-ui/index.html is broken.

**Comment by alperenDagi** [comment]
Fixed but still doesn't show some backendpoints. Why do you think it doesn't show up some functionality?

**Comment by furknbulbul** [comment]
It is fixed now, shows all the endpoints implemented.
