### ISSUE TITLE
Review Class Diagrams

### ISSUE THREAD

**Issue by kubraaksux** [bounswe/bounswe2023group1#243]
### Review Class Diagrams
Revisit class diagrams, check on inconsistencies and fixes.
Consider feedbacks from last semester.
Pursue enhancements.

**Comment by volcaniqueo** [comment]
This is an ongoing issue. Will be continuously reviewed as we implement the backend.

**Comment by volcaniqueo** [comment]
**An important revision has been made. Notable changes are:**
-Separation of _Need_ and _Resource_ classes.
-_Location_ field has been added to the _Need_ class.
-There is no feedback mechanism to the _Action_ class (Actions may be marked as complete/incomplete by the assignee; no feedback is necessary.), _Feedback_ class is related with _Task_ class.

**Comment by kubraaksux** [comment]
UML diagram updates are assigned to the backend team, and mockup reviews are assigned to mobile and web. Since those are better pairings, Requirements specification review task belongs to whole team.

**Comment by volcaniqueo** [comment]
Given our implementation of backend was limited with victim & responder, and the addition of coordinator & facilitator would bring new complexities; our revision for Milestone 1 is very limited. We will make a more detailed revision after we implement the remaining coordinator & facilitator functionalities. Meanwhile, we also decided to provide IntelliJ IDEA auto-generated class diagram for our current implementation (a simplified version) to give more precise information about our backend.
