### ISSUE TITLE
Review Sequence Diagrams

### ISSUE THREAD

**Issue by kubraaksux** [bounswe/bounswe2023group1#244]
### Review Use Case Diagrams
Revisit use case diagrams, check on inconsistencies and fixes.
Consider feedbacks from last semester.
Pursue enhancements.

_That was our weakest part last semester. Should be taken into account. More work and assignee is necessary_

**Comment by volcaniqueo** [comment]
This is an ongoing issue. Will be continuously reviewed as we implement the backend.

**Comment by kubraaksux** [comment]
UML diagram updates are assigned to the backend team, and mockup reviews are assigned to mobile and web. Since those are better pairings, Requirements specification review task belongs to whole team.

**Comment by volcaniqueo** [comment]
Ali made several revisions for this issue, but again as we said for all UML diagrams, we will make a more detailed revision after we implement the coordinator & facilitator functionalities.
