### ISSUE TITLE
Sub-teams

### ISSUE THREAD

**Issue by kubraaksux** [bounswe/bounswe2023group1#246]
### Description
Sub teams will be determined

**Deadline: 10.10.2023**
 
**Frontend Team**

- 

**Backend Team**

-

**Mobile Team**

-

**Comment by volcaniqueo** [comment]
### Description
Sub teams will be determined

**Deadline: 10.10.2023**
 
**Frontend Team**

Kübra
Ilgaz
Orkan

**Backend Team**

Ali
Volkan
Türker
Furkan

**Mobile Team**

Alperen
Çağrı
Harun
Elif
