### ISSUE TITLE
Add New Members to Wiki with Their Personal Pages

### ISSUE THREAD

**Issue by volcaniqueo** [bounswe/bounswe2023group1#253]
New team members should add their bio and update the photo frame accordingly.

**Comment by TurkerErdem99** [comment]
[My personal wiki page](https://github.com/bounswe/bounswe2023group1/wiki/H%C3%BCseyin-T%C3%BCrker-Erdem) is added. [Home Page](https://github.com/bounswe/bounswe2023group1/wiki) is updated accordingly.

**Comment by eliftoklu** [comment]
[My personal wiki page](https://github.com/bounswe/bounswe2023group1/wiki/Elif-Tokluo%C4%9Flu) is added. [Home Page](https://github.com/bounswe/bounswe2023group1/wiki) is updated accordingly.

**Comment by orkana** [comment]
[My personal wiki page](https://github.com/bounswe/bounswe2023group1/wiki/Orkan-Akisu) is added. [Home Page](https://github.com/bounswe/bounswe2023group1/wiki) is updated accordingly.

**Comment by volcaniqueo** [comment]
All new members added their personal page accordingly.
