### ISSUE TITLE
Database Design

### ISSUE THREAD

**Issue by kubraaksux** [bounswe/bounswe2023group1#259]
Start designing database relations while revising class diagrams

**Comment by furknbulbul** [comment]
created initial version of tables, you can view through this [link](https://dbdiagram.io/d/resq-652e4a2bffbf5169f0d73dba)

**Comment by alitpc25** [comment]
Database design is completed with PR https://github.com/bounswe/bounswe2023group1/pull/287. The database schema can be viewed through the link provided above.
