### ISSUE TITLE
Reset Branches

### ISSUE THREAD

**Issue by kubraaksux** [bounswe/bounswe2023group1#263]

**Comment by alitpc25** [comment]
Branches have been reset. From now on, we should be using feature, dev, main, hotfix, release, and bugfix branches. Our convention should be like this: 
feature/BE-255-backend-init-setup
feature/FE-256-frontend-init-setup
feature/MB-257-mobile-init-setup

**Comment by alitpc25** [comment]
What is the reason it is "not done" ?
