### ISSUE TITLE
Update RAM

### ISSUE THREAD

**Issue by kubraaksux** [bounswe/bounswe2023group1#268]
Ram should be updated for cmpe451

**Comment by kubraaksux** [comment]
https://docs.google.com/spreadsheets/d/1b1dIveiJImE1Wcf5tkhszOjz0kskqKGf8slYZ5rLzKE/edit#gid=0

I have updated RAM

- new members are added to the ram
- old rows are cleared
- addeed team/backend/frontend/mobile columns
- updated new rows with the duties till milestone 1

**Comment by ilgazer** [comment]
I think closing this was immature, as @ilgazer @TurkerErdem99 @eliftoklu needs to update their RAM assignments. Also, we also need to resolve the inconsitency
