### ISSUE TITLE
Review Mockups for Mobile

### ISSUE THREAD

**Issue by kubraaksux** [bounswe/bounswe2023group1#269]

**Comment by GulbeycanCagri** [comment]
We reviewed the mockups again before beginning the coding. We prepared new designs. Then, @HarunErgen prepared these designs on Figma. You can visit the [link](https://www.figma.com/file/nQuOOQp2xrVNsoVk31bEZ6/ResQ-Mobile-Android-Application?type=design&node-id=21-7904&mode=design&t=gLZWJEhmEESuqWJT-0) to see our current designs.

**Comment by kubraaksux** [comment]
Yeah i think review of old ones are not sufficient, not making big change and not consistent&harmony with web develop. Actually there are some things that needed to be developed at frontend and not clear at requirements. Some of are even not mentioned at req and some points at req should be revised. So i decided to renew mockups from the beginning. And im on it for some time. There will be completely new and better mockups soon. 
Also i think mockups should always be on up-date. This is crucial for mobile-web communication and consistency. And also same applies for backend too since i had to make frontend implementation a lot of different from old mockups with backends direction. 
I kindly ask to mobile, review their mockups and catch up a standard with frontend.
Tomorrow i'll release new mockups.
Be ready!
Tip for mobile team i found those useful and practical.
You will be faster and your designs will be in rythm with front since we prefer mui library:
[mockup-design-mobile1-iphone](https://www.figma.com/file/F5FAgHB3xKKEUTDufGYnTT/Free-iPhone-Clay-Mockup---By%3A-Dezign_Daddy-(Community)?type=design&node-id=1-246&mode=design&t=IIPddMy5U2NxXmuj-0)
[mockup-design-mobile1-mui-kit](https://www.figma.com/file/6GCqIjL7LkzRE8YQn9OKwh/Medical-Pharmacy-App-UI-Kit-(Figma)-(Community)?type=design&node-id=1-2&mode=design&t=zl9MblxsEqafDe8M-0)

**Comment by kubraaksux** [comment]
sorry guys i had to do this

**Comment by alperenDagi** [comment]
It's not possible to request changes to our mobile design at the last moment, right before the milestone. We've already designed the .apk based on the Figma design. While we can think about adjusting the colors, we can't create new mockups because we've already completed them.

**Comment by kubraaksux** [comment]
Im mentioning this for a couple of weeks, not only colors ofc but also as i mentioned at [this issue](https://github.com/bounswe/bounswe2023group1/issues/290) landing page, role request system, user profile, notifications and many more. But since i tried my best with the effort of communication with my team and with other teams, im not pursuing more.

**Comment by kubraaksux** [comment]
But from this point, i again need to tell mobile and web in very different directions and this will be a problem later.  And since mobile is at the earlier stages in apk -your words and conc from presentation- that would not be a lot of trouble.
I think i tried my best. Good of luck
