### ISSUE TITLE
Page Design Mobile

### ISSUE THREAD

**Issue by kubraaksux** [bounswe/bounswe2023group1#270]

**Comment by HarunErgen** [comment]
We prepared the page design templates as the mobile team. Then, I recreated the pages in Figma based on these templates.

**Comment by HarunErgen** [comment]
@kubraaksux https://www.figma.com/file/nQuOOQp2xrVNsoVk31bEZ6/ResQ-Mobile-Android-Application?type=design&node-id=0-1&mode=design&t=K5JKCr2hCaLKrgC3-0

**Comment by HarunErgen** [comment]
After the discussion with Frontend team:
![image](https://github.com/bounswe/bounswe2023group1/assets/83069560/d319f4b5-0a6c-400f-be85-8ad130149f50)

**Comment by kubraaksux** [comment]
It is so great that we have consistency between mobile and web now. Very Good Work!! Everything seems cool. Designs until the scope of project plan till today is done.
