### ISSUE TITLE
Update Mockups for Frontend

### ISSUE THREAD

**Issue by kubraaksux** [bounswe/bounswe2023group1#271]

**Comment by kubraaksux** [comment]
mockups should be standardized.
all of them should be checked and updated.

- [ ] unregistered user
- [ ] victim
- [ ] responder
- [ ] facilitater
- [ ] coordinater
- [ ] admin

**Comment by ilgazer** [comment]
We also need to synergise the pages we already made using mui with the mockups. I think @kubraaksux 's idea of recreating all the mockups with the mui figma library would be something very productive.

**Comment by kubraaksux** [comment]
yeah im on it, using figma with mui template offers much more presentable and accurate mockups since we are using mui library also at web development. 
You'll be amazed with the work&results guys!!

**Comment by kubraaksux** [comment]
> mockups should be standardized. all of them should be checked and updated.
> 
> * [ ]  unregistered user
> * [ ]  victim
> * [ ]  responder
> * [ ]  facilitater
> * [ ]  coordinater
> * [ ]  admin

those are taken into account when mockups are improved. unregistered user has accepted as victim by default after the meeting with backend.

**Comment by kubraaksux** [comment]
> mockups should be standardized. all of them should be checked and updated.
> 
> * [x]  unregistered user
> * [x]  victim
> * [x]  responder
> * [ ]  facilitater
> * [ ]  coordinater
> * [ ]  admin

Finalized decision is giving unregistered users victim role. In other words default user role is victim. For now, unreg. user, victim and responder mockups updated. Because those are ( unreg. user, victim ) already implemented or currently implementing (responder) nowadays. Also with considering project plan, those are in the scope now. So, these will be sufficient for now and other mockups will be updated when they are implementing. So that, we can make revisions.

**Comment by kubraaksux** [comment]
This is all of my work. I didnt updated, i created all the mockups from the start which in the scope according to the project plan. Also, i have created components and put those aside with the explanation to guide my team for later use. Also, i made a backup for my figma pages, this will save us a lot of time and energy. 
Now, all mockups are created by me and they are in a perfect position. There is no more work.

All of my work:
<img width="763" alt="Screenshot 2023-11-02 at 20 12 21" src="https://github.com/bounswe/bounswe2023group1/assets/67320250/f2ad1d68-7f29-4044-9357-b36126d92ee1">

Components: 
<img width="324" alt="Screenshot 2023-11-02 at 20 16 51" src="https://github.com/bounswe/bounswe2023group1/assets/67320250/cee23bd0-7482-4629-aa08-e5fbe2a7a064">

Pages:
<img width="365" alt="Screenshot 2023-11-02 at 20 17 26" src="https://github.com/bounswe/bounswe2023group1/assets/67320250/97589f83-9643-4fd9-8bf6-4bdbfc674dbe">

Backup:
<img width="291" alt="Screenshot 2023-11-02 at 20 17 47" src="https://github.com/bounswe/bounswe2023group1/assets/67320250/91cbe5f1-d561-4b1f-858e-749372cb69dc">

**Comment by kubraaksux** [comment]
Pages more detailed:
<img width="921" alt="Screenshot 2023-11-02 at 20 18 38" src="https://github.com/bounswe/bounswe2023group1/assets/67320250/299a3050-3478-4ade-954f-592cffe071f6">
<img width="885" alt="Screenshot 2023-11-02 at 20 19 06" src="https://github.com/bounswe/bounswe2023group1/assets/67320250/5665e249-3f6f-4920-b405-635849bc80a7">
<img width="860" alt="Screenshot 2023-11-02 at 20 19 46" src="https://github.com/bounswe/bounswe2023group1/assets/67320250/9a5af99d-9441-47b6-becd-55fbd59b69df">
<img width="864" alt="Screenshot 2023-11-02 at 20 20 02" src="https://github.com/bounswe/bounswe2023group1/assets/67320250/dd19642a-876d-449d-9645-df0751f7ae1e">

**Comment by kubraaksux** [comment]
Components more detailed:
<img width="632" alt="Screenshot 2023-11-02 at 20 20 54" src="https://github.com/bounswe/bounswe2023group1/assets/67320250/0527df77-44ef-44d0-a20b-ea70c4073c52">
<img width="650" alt="Screenshot 2023-11-02 at 20 21 13" src="https://github.com/bounswe/bounswe2023group1/assets/67320250/50f6f5ed-1baf-4976-9b47-e205ec01e974">
<img width="920" alt="Screenshot 2023-11-02 at 20 21 32" src="https://github.com/bounswe/bounswe2023group1/assets/67320250/8d83039f-961a-4b17-a1e1-3833c0e277cf">
<img width="909" alt="Screenshot 2023-11-02 at 20 22 08" src="https://github.com/bounswe/bounswe2023group1/assets/67320250/0a52ceb2-666b-4274-bc92-b39aadc1b48f">
<img width="866" alt="Screenshot 2023-11-02 at 20 22 30" src="https://github.com/bounswe/bounswe2023group1/assets/67320250/0b7d048d-aa85-45d2-afcd-904cee1af8f5">
<img width="486" alt="Screenshot 2023-11-02 at 20 22 41" src="https://github.com/bounswe/bounswe2023group1/assets/67320250/917e7d24-d393-48a2-979b-f17e04bef106">

**Comment by kubraaksux** [comment]
Since after components grouped, it is hard to change. I also copied components before grouped and added as a backup plan. So they will save time and effor later when other mockups are created. Also, im afraid not all of my teammates have experience on figma. So i was afraid that less proficiency at figma could cause destruction of the components, therefore i tried to save us and mockups. 
Backup plan: 
<img width="291" alt="Screenshot 2023-11-02 at 20 23 08" src="https://github.com/bounswe/bounswe2023group1/assets/67320250/1ef686bb-d004-461e-9807-8f29ea6830c8">

**Comment by kubraaksux** [comment]
For now, i'll share my figma mockups with my friends at our communication channel because those are confidential. Just before milestone they will be shared from here.

**Comment by orkana** [comment]
Added responder task page
