### ISSUE TITLE
Initial Authentication and Authorization for each User Roles on Backend

### ISSUE THREAD

**Issue by alitpc25** [bounswe/bounswe2023group1#273]
Initial Authentication and Authorization for each user role should be implemented on the backend and relevant endpoints should be provided for use of the mobile & frontend teams.

As an initial login/register process, users could be able to provide their email, password, and roles to the system and continue if successful. Different verification types will then be added to the login/registration process depending on the user role.

**Comment by kubraaksux** [comment]
great job!
