### ISSUE TITLE
Mobile User Profile Page

### ISSUE THREAD

**Issue by HarunErgen** [bounswe/bounswe2023group1#278]

**Comment by GulbeycanCagri** [comment]
I have coded the view and view model. I need to connect to the backend.

**Comment by GulbeycanCagri** [comment]
I connected it to the backend before the MS1. After storing some variables in the program, I will need to make minor changes. I will also talk about the values returned from getUserInfo endpoint ​​with the backend team.

**Comment by GulbeycanCagri** [comment]
Related PRs are: [327](https://github.com/bounswe/bounswe2023group1/pull/327) and [335](https://github.com/bounswe/bounswe2023group1/pull/335)
