### ISSUE TITLE
Implement location services and disaster reporting mechanism

### ISSUE THREAD

**Issue by furknbulbul** [bounswe/bounswe2023group1#285]
Deciding the location services needed in the application and implement it.

Integrate disaster reporting mechanism by using victim and location services.

**Comment by volcaniqueo** [comment]
Disaster reporting will be available to all user roles and will be implemented prior to milestone 1

**Comment by volcaniqueo** [comment]
After talking with the team, we agreed on the necessity to learn annotation concepts for these implementations; thus decided to postpone for Milestone 2/3. This has been decided long before (One day after from 4th Lab), but I forgot to update to issue with this comment.

**Comment by furknbulbul** [comment]
Annotations and those services are implemented and deployed, closing the issue now.
