### ISSUE TITLE
Implement disaster reporting - Mobile

### ISSUE THREAD

**Issue by volcaniqueo** [bounswe/bounswe2023group1#295]
Mobile team will implement the disaster report page which is available to all users.

**Comment by alperenDagi** [comment]
Please ask us before opening our issue.

**Comment by volcaniqueo** [comment]
I opened this issue while talking with Elif during 4th lab.

**Comment by volcaniqueo** [comment]
> Please ask us before opening our issues.


I opened this issue while talking with Elif during 4th lab.

**Comment by volcaniqueo** [comment]
> Please ask us before opening our issues.

I opened this issue while talking with Elif during 4th lab.

**Comment by alperenDagi** [comment]
Map can be used for disaster reporting.
