### ISSUE TITLE
User Case Scenario For Web Page

### ISSUE THREAD

**Issue by eliftoklu** [bounswe/bounswe2023group1#299]
User case scenario of the web page must be prepared for the milestone 1.

Due to 31.10.2023

**Comment by ilgazer** [comment]
A user case scenario was prepared for the presentation today. @kubraaksux has it in text form so we can deliver it

**Comment by kubraaksux** [comment]
"Melek's Transition to ResQ Responder: A Tale of Gratitude and Empowerment"
If she wasnt registered
Disaster Strikes - No Previous Account:
* When the disaster strikes Istanbul, Melek realizes she doesn't have an existing "ResQ" account, as she hadn't needed one before. Now, in the midst of this emergency, she needs to sign up quickly to access the app's resources and assistance.
2. Signing Up:
* Melek visits the "ResQ" website on her computer, where she is greeted with the sign-up page. She provides her email, creates a password, and agrees to the terms of service, ensuring that she provides the correct credentials.
3. Account Creation Success:
* Melek's account is successfully created, and she is directed to the login page.
4. Logging In:
* Melek logs in with her newly registered credentials, gaining access to the "ResQ" platform.

But for melek
1. Introduction:
* After a heartwarming experience with the "ResQ" app, where she received timely assistance during a crisis, Melek decides to give back by becoming a ResQ Responder. She's determined to make a difference in her community.
2. Logging In:
* Melek revisits the "ResQ" platform, this time on her computer. She logs in with her existing account credentials, and her familiar ResQ homepage appears.
. Choosing Her Role:
* Upon signing in, Melek is directed to the user role page. By default, all users are assigned the 'Victim' role. Here, she can select a different role that suits her current situation later on if she made a request and it is approved.
* All Roles:  These roles can include 'Victim,' 'Responder,' ‘Facilitator,’ 'Coordinator,' or ‘Admin.’ Each role has its unique set of permissions and responsibilities within the platform.
* Basically, victim user is default and who is effected from disaster and needs help. Responders are resource providers, facilitators are people that manage resource allocation and crisis control at the area. Coordinators who coordinate all these actions between facilitator and responders. Action and resource coordinators. Admins are system admins.
Map Listing Resources: 	Victim users are directed to the map which shows resources they needed as pins in the map. This is a visual representation on the "ResQ" app that shows various icons or pins on a map. Each of these icons or pins represents a resource such as a distribution center for supplies, medical facilities, or volunteer stations.
Melek can go to account and save her profile details or can update:
* This part highlights that Melek, as a user on the "ResQ" platform, has control over her profile information. She can visit her user account settings, which is often referred to as the 'Account' section, and do two main actions:
    * Save Profile Details: Melek can input and save her personal information, such as her name, birthdate, and any additional details required by the platform. Saving this information helps create a comprehensive user profile, making it easier for others to identify her and vice versa.
    * Update Profile: If Melek's personal information changes or if she wants to add or modify any details, she can use the 'Update' function to keep her profile current. This ensures that her profile is accurate and up-to-date.
From here, Melek can again request for a role - She makes a request for a responder role:
* Within the same 'Account' section of her profile settings, Melek can request a change in her role. In the "ResQ" app, users are assigned roles like 'Victim,' 'Responder,' or other relevant designations that define their capabilities and responsibilities.
* Melek decides to change her role from 'Victim' to 'Responder' to actively participate in disaster relief efforts.
* 		She drags her ID from her computer and confirms:
    * As part of her role change request, Melek is prompted to provide additional documentation to verify her identity and suitability for the 'Responder' role. In this case, she is asked to upload her ID, which could be a government-issued identification document.
    * Once Melek uploads her ID and confirms her role change request, the platform uses this documentation to ensure her identity and eligibility for the 'Responder' role.
* 		With the approval notification, she is directed to sign in again:
    * After the platform reviews her request and approves her role change, Melek receives a notification indicating the successful role transition.
    * To activate her new role, she is directed to log in once again, where she can now select the 'Responder' role.
* 		Now with her new login and the 'Responder' role selected, she can use the app as a responder:
    * Melek is now logged into the "ResQ" app with the 'Responder' role activated. This means she can access features and tools specific to responders, allowing her to actively engage in disaster relief activities and help those in need.

8. Helping Others:
* Melek quickly springs into action. With the skills and resources at her disposal, she rushes to the location where assistance is needed, ready to make a positive impact, just as others did for her in the past.
9. The Circle of ResQ:
* Melek's journey on the "ResQ" platform comes full circle. She once sought help and found it, and now she's actively participating in providing support to others in their time of need.
10. A Grateful Melek:
* Melek is profoundly grateful for the opportunity to give back to her community through the "ResQ" platform. Her own experience as a 'Victim' and her transformation into a 'Responder' exemplify the power of community and compassion during times of disaster.

**Comment by kubraaksux** [comment]
we supported use case story with actual id upload at presentation
id belongs to melek
