### ISSUE TITLE
Frontend Implement Jwt Based Authentication For Login And Queries

### ISSUE THREAD

**Issue by eliftoklu** [bounswe/bounswe2023group1#300]
Implement jwt based authentication for login and queries

**Comment by ilgazer** [comment]
Thank you @kubraaksux for doing most of the work for implementing a majority of this feature! I will just fix the errors and get it ready for a PR.

**Comment by kubraaksux** [comment]
[326](https://github.com/bounswe/bounswe2023group1/pull/326)
[330](https://github.com/bounswe/bounswe2023group1/pull/330)
