### ISSUE TITLE
Multirole Implementation at Frontend - Userrole Page

### ISSUE THREAD

**Issue by kubraaksux** [bounswe/bounswe2023group1#303]
After the meeting today, it has concluded that with the event of submission at the sign in page, page will be directed to user role page. 
And user will have victim role by default. with this role, user can open request for other roles. after the acceptance of those requests, accepted roles will be returned as a list from backend and they will appear at the user role page. 
User can choose one user role at the time, but at different times can log in with other user roles. 
This enables multirole functionality.

**Comment by kubraaksux** [comment]
#302

**Comment by ilgazer** [comment]
Resolved by #340 , which builds on #302
