### ISSUE TITLE
Editing the meeting notes template and publishing Meeting 2 Notes on the Wiki

### ISSUE THREAD

**Issue by volcaniqueo** [bounswe/bounswe2023group1#32]

**Comment by volcaniqueo** [comment]
Find the meeting notes [here](https://github.com/bounswe/bounswe2023group1/wiki/Meeting-2-(08.03.2023)).

**Comment by volcaniqueo** [comment]
Revisioner column added to the template. Find the template [here](https://github.com/bounswe/bounswe2023group1/wiki/Meeting-Notes-Template).

**Comment by furknbulbul** [comment]
I had added the issues that was opened to action items. Great work
