### ISSUE TITLE
DELIVERABLES- ATTENTION ALL TEAM MEMBERS

### ISSUE THREAD

**Issue by kubraaksux** [bounswe/bounswe2023group1#355]
We need to complete all deliverables due 03.11.2023

- [x] Software Requirements Specification
- [x] Software Design (UML diagrams)
- [x] Scenarios and Mockups
- [x] Project Plan, Communication Plan, Responsibility Assignment Matrix
- [x] Weekly reports and any additional meeting notes
- [x] Milestone Review 
- [x] Individual Contributions 
- [x] A pre-release version of your software 

Effort from all team members necessary and expected
Especially we expect requirements help from new team members so, we can understand how clear and precise is our requirements specification
Please specify issue and mention here when resolved
I'll try to follow all and manage absent work
Good Luck!

**Comment by kubraaksux** [comment]
[mockups-mobile](https://github.com/bounswe/bounswe2023group1/issues/269) - needs to be revised and done

**Comment by kubraaksux** [comment]
[Software Requirements Specification](https://github.com/bounswe/bounswe2023group1/issues/240)
All team members need to contribute this. Contribution necessary.

**Comment by kubraaksux** [comment]
[create communication plan](https://github.com/bounswe/bounswe2023group1/wiki/Cmpe-451-Communication-Plan)
check out 
https://github.com/bounswe/bounswe2023group1/wiki/Cmpe-451-Communication-Plan

**Comment by kubraaksux** [comment]
i had already completed "update ram" weeks before.
it is done.
[Update RAM](https://github.com/bounswe/bounswe2023group1/issues/268)

**Comment by GulbeycanCagri** [comment]
I have added a [draft](https://github.com/bounswe/bounswe2023group1/blob/main/reports/m1_group1.md).
