### ISSUE TITLE
Further Requirement Revision

### ISSUE THREAD

**Issue by ilgazer** [bounswe/bounswe2023group1#365]
I believe that the requirement page, even after v0.3.0, requires revision to its language to make it more formal and clearer. Also I will further clarify what each user should be able to view and do in the map and as a list. This reflects the team's vision of the map as shown in the demo and will incorporate the feedback regarding being able to view things as a list from the customers.

**Comment by kubraaksux** [comment]
> I believe that the requirement page, even after v0.3.0, requires revision to its language to make it more formal and clearer. Also I will further clarify what each user should be able to view and do in the map and as a list. This reflects the team's vision of the map as shown in the demo and will incorporate the feedback regarding being able to view things as a list from the customers.

It has v0.3.1 already

**Comment by kubraaksux** [comment]
https://github.com/bounswe/bounswe2023group1/wiki/Requirements-Revision-for-Cmpe451-%E2%80%90v2-%E2%80%90%E2%80%90-Req-Version-0.3.1
