### ISSUE TITLE
Map - Data Table Component Customized for Search and Filter

### ISSUE THREAD

**Issue by kubraaksux** [bounswe/bounswe2023group1#378]
Development of a data table component designed to enhance the functionality of our map search and filtering system. The data table component will allow users to interact with and visualize location-based data more effectively, facilitating an improved user experience for searching and filtering.
Shows name, type, quantity, location

**Comment by ilgazer** [comment]
Isn't this the same as #373? You can take the issue if you want and we can close one of them

**Comment by kubraaksux** [comment]
At lab we shared tasks with you, i got the data table component with search inside of it and filtering inside of it. you got search at the map. so, this issue exactly mine and description shows my duties, 373 is your issue and should define your tasks. you can go ahead to 373.
