### ISSUE TITLE
Creation of Ongoing Task Screen

### ISSUE THREAD

**Issue by alperenDagi** [bounswe/bounswe2023group1#391]
Ongoing Tasks screen button should be added to user profile.
Navigation from user profile to Ongoing Tasks shall be implemented.
Ongoing Tasks screen shall be created .

**Comment by GulbeycanCagri** [comment]
I have create Ongoing Tasks screen. I will add button and navigation functionality to the profile when I update the codes for user profile. Please check PR #412 .

**Comment by GulbeycanCagri** [comment]
Closed for now.
