### ISSUE TITLE
Creating and Editing Labels for Improved Issue Management

### ISSUE THREAD

**Issue by kubraaksux** [bounswe/bounswe2023group1#4]
Hello everyone,

I'm proposing some changes to the labels we use on this project to improve our issue management and make it easier for contributors to identify issues that need attention.

First, I suggest that we create a set of standardized labels that we can use consistently across all issues. This will help us to categorize and prioritize issues more effectively. Some possible labels we could use include:

Priority: to indicate the urgency of an issue
Type: to indicate the type of issue (bug, feature request, enhancement, etc.)
Status: to indicate the current status of the issue (open, in progress, closed, etc.)

I also recommend that we create a guide or documentation for how to use these labels effectively. This could include guidelines on when to use each label, how to update labels as the status of an issue changes, and how to use labels in conjunction with other issue management tools (such as milestones or assignees).

As for now, existing labels seems great. Im editing them a bit, and adding new ones. Trying to make colors more convenient. If you have any suggestion let me know!

Let's make good labels for an effective issue management system.

**Comment by kubraaksux** [comment]
some conventions for label use that i found:

Priority
   High Priority: #b60205 (red)
   Medium Priority: #d93f0b (orange)
   Low Priority: #0e8a16 (green)

Bug
   Bug: #d73a4a (red)
   Needs Triage: #fbca04 (yellow)
   Duplicate: #cfd3d7 (gray)
   Won't Fix: #ffffff (white)

Enhancement:
   Enhancement: #a2eeef (teal)
   Feature Request: #d4c5f9 (purple)
   Refactor: #6f42c1 (indigo)

Documentation:
   Documentation: #0075ca (blue)
   Help Wanted: #008672 (dark green)
   Question: #d876e3 (pink)

Type:
   Type: #bfe5bf (light green)
   Bug: #ee0701 (bright red)
   Feature: #05c49f (turquoise)
   Enhancement: #5319e7 (violet)

**Comment by kubraaksux** [comment]
I checked some repositories for labelling. Tried to follow the convention. Kubernetes and VS Code is very successful in terms of labeling

**Comment by kubraaksux** [comment]
Added milestone and lifecycle labels too. Not so essential for now but may be useful later

**Comment by kubraaksux** [comment]
kept lifecycle active because we can need updates for labels

**Comment by alperenDagi** [comment]
Great work 💯
