### ISSUE TITLE
Implement Responder My Tasks Page

### ISSUE THREAD

**Issue by orkana** [bounswe/bounswe2023group1#420]
Responder can update the status  of tasks: to do, in progress, completed. Task list also should be sorted by their status.

**Comment by ilgazer** [comment]
To fulfill two of the main requirements of responder, which is displaying which tasks a responder can accept/has accepted/previously completed as a list and on the map, as well as change this state, a page with a list and a map similar to the victim's main page will be implemented. Actions will be displayed as arrows and resources as points.

**Comment by ilgazer** [comment]
By implementing the task management screen for responders, #602 resolves this issue
