### ISSUE TITLE
Develop map based interfaces for warnings, disaster occurrences, and actions

### ISSUE THREAD

**Issue by furknbulbul** [bounswe/bounswe2023group1#425]
* Map operation related to the action
* Disaster related informations, warnings  on map (involves implementing the new entity - service - controller type)

those backend functionalities should be covered this week.

**Comment by ilgazer** [comment]
As per our discussion with the TA's, disaster related information and warnings on map are supposed to be shown using annotations. How do you think we should proceed?

**Comment by furknbulbul** [comment]
This feature is already implemented.
