### ISSUE TITLE
Implement digital resource management, categorization, dynamic needs adaptation

### ISSUE THREAD

**Issue by furknbulbul** [bounswe/bounswe2023group1#426]
Victims' needs varies as repeatable needs and one time needs. We need to implement and behave those needs accordingly.
Categorization of resources should be changed accordingly too.

**Comment by volcaniqueo** [comment]
I think this issue is ambiguous. Please refer to the #559 for dynamic need implementation. Also, I will open a new issue for the rest; improving resource categorization, please refer to the #586 for it.
