### ISSUE TITLE
Adding date created field to actions, requests and resources

### ISSUE THREAD

**Issue by ilgazer** [bounswe/bounswe2023group1#470]
As per the customer's request in the customer meeting and matching the implementation in #469, is there a chance you could add a "date created" field to actions, requests and resources?

**Comment by furknbulbul** [comment]
Backend added the date created field to endpoints, you can view the [pull request](https://github.com/bounswe/bounswe2023group1/pull/471)

**Comment by ilgazer** [comment]
Resolved in #471
