### ISSUE TITLE
Creating and Editing the Requirements

### ISSUE THREAD

**Issue by furknbulbul** [bounswe/bounswe2023group1#52]
We have held a meeting to determine requirements last week. We should document them on our wiki page.

**Comment by kubraaksux** [comment]
some ideas i found useful: 
https://github.com/bounswe/bounswe2022group2/wiki/Requirements
https://github.com/bounswe/bounswe2022group3/wiki/Practice-App-Requirements
https://github.com/bounswe/bounswe2022group6/wiki/Requirements
https://github.com/bounswe/bounswe2022group7/wiki/Requirements-(Draft)

**Comment by furknbulbul** [comment]
They are on the wiki now, thanks @alperenDagi
