### ISSUE TITLE
Write our progress for our requirements for ML2 Report

### ISSUE THREAD

**Issue by ilgazer** [bounswe/bounswe2023group1#520]
Provide progress according to requirements: being either not started, in progress, or completed (completed = implemented, tested, documented, and deployed)

**Comment by ilgazer** [comment]
Kübra did look at them from the perspective of the frontend, I think mobile should as well.

**Comment by kubraaksux** [comment]
[check](https://github.com/bounswe/bounswe2023group1/issues/531)
