### ISSUE TITLE
Create Evaluation of Project Deliverables and Impact Analysis on Project Plan

### ISSUE THREAD

**Issue by kubraaksux** [bounswe/bounswe2023group1#529]
## Summary
I have evaluated our project deliverables and their impact, also i have added those to the project plan.

## Objectives

1. **Deliverable Review:**
   - Conduct a thorough review of all project deliverables completed in the current phase.
   - Ensure each deliverable meets the quality standards and requirements initially outlined.

2. **Impact Analysis:**
   - Analyze the impact of these deliverables on the overall project plan.
   - Determine if the completion of these deliverables has affected the project timeline, resource allocation, or scope.

3. **Identification of Discrepancies:**
   - Identify any discrepancies between planned and actual project outcomes.
   - Highlight areas where deliverables have exceeded or fallen short of expectations.

4. **Adjustment Recommendations:**
   - Propose adjustments to the project plan based on the evaluation.
   - Suggest changes in timelines, resources, or scope as needed to align with project goals.

5. **Stakeholder Communication:**
   - Communicate findings and recommendations to all relevant stakeholders.
   - Ensure transparency and alignment on any proposed changes to the project plan.

## Goal
The primary goal of this issue is to ensure that our project remains on track towards achieving its objectives, within the defined scope and timeline. This evaluation will help us make informed decisions about the future direction of the project, ensuring efficient use of resources and overall project success.

**Comment by ilgazer** [comment]
I think this sueprsedes #519, which I am closing

**Comment by ilgazer** [comment]
Also, I made a small adjustment to the deliverable date table, other than that, really nice work.
