### ISSUE TITLE
Research/start  on annotation for backend

### ISSUE THREAD

**Issue by furknbulbul** [bounswe/bounswe2023group1#544]
Customer wanted us to use annotation, so backend team should learn the how to achieve it and start implementing it.

**Comment by volcaniqueo** [comment]
We will discuss the implementation details in the upcoming meeting. Please refer to the #587 for the details.

**Comment by volcaniqueo** [comment]
Annotation implementation for the backend has been completed. Please refer to the #599 for the details.
