### ISSUE TITLE
Annotation Meeting with the Backend Team

### ISSUE THREAD

**Issue by volcaniqueo** [bounswe/bounswe2023group1#587]
Backend team will conduct a meeting about annotation and members will finalize the implementation schema and implementation will be finished upon Final Milestone.

**Comment by volcaniqueo** [comment]
The meeting will be held today, as agreed by the backend team. Also #591 will be discussed.

**Comment by alitpc25** [comment]
Yesterday(23.12.2023), we met with @ilgazer, talked about how to implement the annotation server and I implemented & deployed it in 4-5 hours.
