### ISSUE TITLE
Creating Custom Templates for Consistent Issue Reporting

### ISSUE THREAD

**Issue by kubraaksux** [bounswe/bounswe2023group1#6]
Hello everyone,

I'm proposing that we create custom templates for issue reporting on this project. Having standardized templates will make it easier for contributors to report issues and help us to ensure that all necessary information is included.

Creating custom templates will also improve consistency in issue reporting, which will make it easier for us to review and prioritize issues. By standardizing the way we report issues, we can eliminate confusion and misunderstandings that can arise when contributors use different formats or omit important information.

Some elements that could be included in our issue templates are:

-A brief description of the issue
-Steps to reproduce the issue (if applicable)
-Expected vs. actual behavior
-Screenshots or other relevant attachments
-Information about the environment where the issue occurred (operating system, browser, etc.)

By including these elements in our issue templates, we can ensure that all issues are reported in a consistent and comprehensive manner, which will save time and effort in the long run.

I suggest that we work together to create and test a set of templates that we can use for different types of issues. We can also update and modify the templates as needed based on feedback from contributors and our own experience.

So we can share the issue creating task together if there are volunteers!

**Comment by ilgazer** [comment]
I have created a [draft for an issue template](https://github.com/bounswe/bounswe2023group1/wiki/Issue-Template), referring to [this example](https://github.com/stevemao/github-issue-templates/blob/master/conversational/ISSUE_TEMPLATE.md) for inspiration. 

I felt that separate templates for different categories of Issue would make sense, as we are answering different questions for a bug/feature request and for a question/task. Do you think we should elaborate further on the questions or is it enough?

Could you @cemsarpkaya take a look at it?

**Comment by ilgazer** [comment]
We discussed the issue template in our last meeting, and it seems to be acceptable.
