### ISSUE TITLE
IP address change

### ISSUE THREAD

**Issue by alitpc25** [bounswe/bounswe2023group1#615]
Due to a slow-down in our ec2 instance, i stopped and started it, and the IP address changed. I will update the README.md accordingly. In addition, mobile and frontend teams should change their code according to the new address.

**Comment by ilgazer** [comment]
The DNS records for api.resq.org.tr were updated accordingly.

**Comment by alitpc25** [comment]
New IP Address is 51.20.138.139 @ilgazer @alperenDagi
