### ISSUE TITLE
Requirements -1.1 User Req

### ISSUE THREAD

**Issue by kubraaksux** [bounswe/bounswe2023group1#66]
Updates on requirements.
Specifically changes on disaster management features related to functional requirements. Namely, user requirements.
We have improvements here originated from mock-up scenarios.

**Comment by GulbeycanCagri** [comment]
Coordinator and Responder sections are added to Google docs. You can contact me to discuss any changes. You can directly add any further requirements. I will be checking them.

**Comment by GulbeycanCagri** [comment]
Closed for now.

**Comment by volcaniqueo** [comment]
We appreciate any feedback. Don't hesitate to suggest new requirements.

**Comment by volcaniqueo** [comment]
Admin role requirements should be added. Thus, I reopen the issue.

**Comment by volcaniqueo** [comment]
I added the admin role. Any additions are welcomed.
