### ISSUE TITLE
MOCK-UP #1 - Coordinator

### ISSUE THREAD

**Issue by kubraaksux** [bounswe/bounswe2023group1#68]
Mock-up scenario 1: Coordinator
Decision maker and action taker.

**Comment by ilgazer** [comment]
We have created a draft of the mockup for the weekly meeting on 25th March Saturday. @HarunErgen will be updating the text of the mockup based on the changes we agreed to in the meeting. Following that, and following the creation of the common mockup template in #72, I will be creating the mock UIs and updating the requirements as per #82.

**Comment by HarunErgen** [comment]
User profile, preconditions and scenario have been added.

**Comment by ilgazer** [comment]
I reviewed the updates to the preconditions and the scenario and they look really good. I made some minor changes in order to facilitate the mock process and added them to the wiki page. I made the figma mocks for the coordinator based on your story. Please check them when you have time.

**Comment by ilgazer** [comment]
Based on positive response from the team, the mockup is complete.
