### ISSUE TITLE
MOCK-UP #3 - Responder

### ISSUE THREAD

**Issue by kubraaksux** [bounswe/bounswe2023group1#70]
Mock-up scenario 3: Responser
Resource provider.

**Comment by alitpc25** [comment]
We completed User Profiles, Conditions, Scenarios, and Addressed Requirements collaboratively.

**Comment by alitpc25** [comment]
Completed Responder Mockups in collaboration with @GulbeycanCagri.

**Comment by alitpc25** [comment]
Updated mockups, revision needed.

**Comment by GulbeycanCagri** [comment]
Revision done.

**Comment by GulbeycanCagri** [comment]
Corresponding requirements edited.

**Comment by GulbeycanCagri** [comment]
@alitpc25 and I decided to close the issue after a final review.
