### ISSUE TITLE
VISUALIZATION OF MOCK-UPS

### ISSUE THREAD

**Issue by kubraaksux** [bounswe/bounswe2023group1#72]
Mock up drawings needed to be done for better representation.

**Comment by kubraaksux** [comment]
Updates on that one will be held during the project lifecycle

**Comment by furknbulbul** [comment]
We have started it and design some, needs improvement. can view [link](https://www.figma.com/file/LmUQJGetWO7oD8qCHAwtbl/login-(Community)?node-id=103%3A1008&t=rHQBYaawSEbLmmG3-1)

**Comment by furknbulbul** [comment]
Working with @alperenDagi

**Comment by kubraaksux** [comment]
#68 #69 #70 #71
