### ISSUE TITLE
Formalizing the Requirements According to SRS

### ISSUE THREAD

**Issue by kubraaksux** [bounswe/bounswe2023group1#79]
` For our software development process, we need to formalize the requirements for our project in accordance with the Software Requirements Specification (SRS) document.
 This document outlines the functional and non-functional requirements for the software system, as well as any constraints or assumptions that need to be taken into account. `

`To formalize the requirements, we need to create 
* a clear and concise list of all the requirements identified in the SRS document, 
* along with their associated priority, dependencies, and any other relevant details. 
* We also need to ensure that the requirements are traceable, meaning that they can be traced back to specific user needs or business goals.` 

`To accomplish this task, we will need to collaborate closely with stakeholders and subject matter experts to ensure that all requirements are captured accurately and completely. `

**Comment by kubraaksux** [comment]
This task is done collaboratively according to our work sharing from meetings. Personally it is very well done.

**Comment by kubraaksux** [comment]
- 1.2.1 Multi-hazard support #62  @CotSezer 
- 2.1 Security and Privacy #63  @cemsarpkaya 
- 1.2.4. Event Creation - 1.2.5. Action Creation - 1.2.6. Action Tracking #65 @HarunErgen 
- 1.2.3 Resource Management #67

**Comment by kubraaksux** [comment]
i edited the user requirements -victim after my mock-up

**Comment by alperenDagi** [comment]
Applied requirement changes according to meeting 10 notes .
