### ISSUE TITLE
Use Case Diagram - Facilitator

### ISSUE THREAD

**Issue by HarunErgen** [bounswe/bounswe2023group1#90]
Diagram creation for user case of _Facilitator_.

**Comment by HarunErgen** [comment]
I combined the common use cases Request, Action, Map and Filter into blocks and distributed them to Facilitator and other relevant actors.

**Comment by HarunErgen** [comment]
With @volcaniqueo, Profile and Log have been combined into blocks and distributed to registered actors.

**Comment by HarunErgen** [comment]
Use cases for Facilitator are completed. Added to the diagram https://app.diagrams.net/#G1-n_7oBebrlLsvjgJWe2yo_4lnmjDpgdR in #94.

**Comment by volcaniqueo** [comment]
I appreciate the block idea since it improves visuality a lot, and also I will be adding to the diagram if some of the requirements related with facilitator are still missing.
