### ISSUE TITLE
Use Case Diagram - Victim

### ISSUE THREAD

**Issue by GulbeycanCagri** [bounswe/bounswe2023group1#94]
Use case diagram creation for the victim role.

**Comment by alitpc25** [comment]
Distributed the work as:
Ali: 
- Register
- Providing Info
- Change Password
- Report Needs
- Get Notification.

Çağrı: 
- Log-in / Log-out
- See Important Locations 
- Display Contact Information For Aid Organizations.
- Filter Aid Organizations By Proximity To Their Location. 
- See and Connect To Facilitators

**Comment by alitpc25** [comment]
Completed diagram is on https://app.diagrams.net/#G1-n_7oBebrlLsvjgJWe2yo_4lnmjDpgdR

**Comment by alitpc25** [comment]
Completed successfully victims use cases in collaboration with @GulbeycanCagri.
